[package]
name = "extract"
version = "0.1.0"
edition = "2024"

[dependencies]
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "extract"
path = "src/extract.rs"
